export const GET_DATA_PRODUCT = "GET_DATA_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const UPDATE_PRODUCT_QUANTITY_FROM_CART = "UPDATE_PRODUCT_QUANTITY_FROM_CART";